[config]
scheme = "dark"
format = "rgb"

[templates.colors]
input_path = "/home/jose/.config/matugen/templates/colors.tpl"
output_path = "/home/jose/.config/hypr/config/colors.conf"
post_hook = "sed -i 's/, /,/g' /home/jose/.config/hypr/config/colors.conf"
